from app.models.analysis import AnalysisResult


def generate_html_report(analysis: AnalysisResult) -> str:
    skills_json = ",".join(f'"{s.name}": {s.score}' for s in analysis.skills)
    exp_json = ",".join(
        f'{{"company": "{e.company}", "role": "{e.role}", "years": {e.duration_years}}}'
        for e in analysis.experience
    )
    edu_json = ",".join(
        f'{{"institution": "{e.institution}", "degree": "{e.degree}", "year": "{e.year}"}}'
        for e in analysis.education
    )

    svg_score = _generate_score_svg(analysis.overall_score)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Resume Analysis Report</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f9fafb; color: #111827; padding: 40px; max-width: 900px; margin: 0 auto; }}
  .header {{ text-align: center; margin-bottom: 40px; }}
  .header h1 {{ font-size: 28px; margin-bottom: 8px; }}
  .score-section {{ display: flex; justify-content: center; margin-bottom: 30px; }}
  .summary {{ background: #fff; padding: 20px; border-radius: 12px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); margin-bottom: 24px; line-height: 1.6; }}
  .grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 24px; }}
  .card {{ background: #fff; padding: 20px; border-radius: 12px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}
  .card h2 {{ font-size: 18px; margin-bottom: 12px; border-bottom: 2px solid #3b82f6; padding-bottom: 8px; }}
  .tag {{ display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 13px; margin: 4px; }}
  .tag-green {{ background: #dcfce7; color: #166534; }}
  .tag-amber {{ background: #fef3c7; color: #92400e; }}
  .tag-blue {{ background: #dbeafe; color: #1e40af; }}
  .tag-purple {{ background: #f3e8ff; color: #6b21a8; }}
  .list {{ list-style: none; }}
  .list li {{ padding: 6px 0; border-bottom: 1px solid #f3f4f6; }}
  .list li:last-child {{ border-bottom: none; }}
  .footer {{ text-align: center; color: #9ca3af; font-size: 12px; margin-top: 40px; }}
  @media print {{ body {{ background: #fff; padding: 20px; }} .card {{ box-shadow: none; border: 1px solid #e5e7eb; }} }}
</style>
</head>
<body>
<div class="header">
  <h1>AI Resume Analysis Report</h1>
  <p>{analysis.years_of_experience:.1f} years of experience &middot; Recommended: {", ".join(analysis.recommended_roles[:3])}</p>
</div>
<div class="score-section">{svg_score}</div>
<div class="summary"><strong>Summary:</strong> {analysis.summary}</div>
<div class="grid">
  <div class="card">
    <h2>Strengths</h2>
    <ul class="list">{"".join(f"<li>{s}</li>" for s in analysis.strengths)}</ul>
  </div>
  <div class="card">
    <h2>Areas for Improvement</h2>
    <ul class="list">{"".join(f"<li>{w}</li>" for w in analysis.weaknesses)}</ul>
  </div>
</div>
<div class="card" style="margin-bottom:24px">
  <h2>Skills Assessment</h2>
  <ul class="list">{"".join(f"<li>{s.name}: <strong>{s.score}/10</strong></li>" for s in analysis.skills)}</ul>
</div>
<div class="card" style="margin-bottom:24px">
  <h2>Experience</h2>
  <ul class="list">{"".join(f"<li><strong>{e.role}</strong> at {e.company} ({e.duration_years:.1f}y)</li>" for e in analysis.experience)}</ul>
</div>
<div class="card" style="margin-bottom:24px">
  <h2>Career Suggestions</h2>
  <ol class="list">{"".join(f"<li>{s}</li>" for s in analysis.career_suggestions)}</ol>
</div>
<div style="display:flex;gap:12px;flex-wrap:wrap;margin-bottom:24px">
  <div><strong>Recommended Roles:</strong> {"".join(f'<span class="tag tag-blue">{r}</span>' for r in analysis.recommended_roles)}</div>
</div>
<div style="display:flex;gap:12px;flex-wrap:wrap">
  <div><strong>Skill Gaps:</strong> {"".join(f'<span class="tag tag-purple">{g}</span>' for g in analysis.skill_gaps)}</div>
</div>
<div class="footer"><p>Generated by AI Resume Analyzer</p></div>
</body>
</html>"""


def _generate_score_svg(score: int) -> str:
    if score >= 80:
        color = "#16a34a"
    elif score >= 60:
        color = "#2563eb"
    elif score >= 40:
        color = "#ea580c"
    else:
        color = "#dc2626"

    radius = 60
    circumference = 2 * 3.14159 * radius
    offset = circumference * (1 - score / 100)

    return f"""<svg width="160" height="160" viewBox="0 0 160 160">
  <circle cx="80" cy="80" r="{radius}" fill="none" stroke="#e5e7eb" stroke-width="12"/>
  <circle cx="80" cy="80" r="{radius}" fill="none" stroke="{color}" stroke-width="12"
    stroke-dasharray="{circumference}" stroke-dashoffset="{offset}" stroke-linecap="round"
    transform="rotate(-90 80 80)"/>
  <text x="80" y="75" text-anchor="middle" font-size="32" font-weight="bold" fill="#111827">{score}</text>
  <text x="80" y="95" text-anchor="middle" font-size="14" fill="#6b7280">/ 100</text>
</svg>"""
